extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss
  - stylelint-config-prettier

plugins:
  - stylelint-scss

rules:
  indentation: 2
  string-quotes: 'double'
  color-hex-case: 'lower'
  declaration-empty-line-before: null
  at-rule-no-unknown: null
  scss/at-rule-no-unknown: true
  scss/no-global-function-names: null
